### ISSUE TITLE
NAMED_CONF not passed to named during start

### ISSUE THREAD

**Issue by spacefreak86** [erayaslan/eras-overlay#1]
The current init sript for named does not pass the NAMED_CONF variable to named via -c option during start, but this is mandatory if someone wants to run multiple instances on the same host.
The work-around is to add the -c option to the OPTIONS variable with the same value as NAMED_CONF, but this is very misleading.

I suggest to change the start-stop-daemon command like this:

start-stop-daemon --start --pidfile ${PIDFILE} \
                --nicelevel ${NAMED_NICELEVEL:-0} \
                --exec /usr/sbin/named \
                -- -u named -c "${NAMED_CONF}" ${CPU} ${OPTIONS}

What do you think about that?

**Comment by erayaslan** [comment]
yeah, it is surprising that NAMED_CONF in /etc/conf.d/named is not taken into account during daemon start up. Fixed via 739c3a5

Thanks
